name = "backend"
compatibility_date = "2024-09-30"
compatibility_flags = [ "nodejs_compat" ]

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiM2U4ZDEwZWYtOTIyNC00YmIyLTg1NzQtNTZhMzljNmEzODkwIiwidGVuYW50X2lkIjoiNDJjYWI0YjkxMzJmOGM4YzNlYmU0ZjFhNDNkNTAzMGY4MWIxMjdjZDVkODVmZTYyYzA2OTNiM2Y3MzM0MWIzNiIsImludGVybmFsX3NlY3JldCI6Ijg3NDg2NmM1LTk5NTQtNGNhMi1iNDVhLTFmMzE2NzM2NDg5MSJ9.dsaRXy4Evt2mUhkyJyWyEpJZDiWD2nTFymvVWBR3c2Y"
JWT_SECRET = "123456"