name = "backend"
compatibility_date = "2024-09-30"
compatibility_flags = [ "nodejs_compat" ]

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiMmRjMWRlNGEtNzZjZi00NTk2LThmY2YtNDQzOGNlYjVmMWFhIiwidGVuYW50X2lkIjoiNjgyNTYxMjdmYTVmNzY0ZmM4NjRkNTQ0ZDg3ZDY5NWIxYzQ1MDUyNDE5OWEwNWQxYjgyZTNiYTQ1NjNjZDNhYiIsImludGVybmFsX3NlY3JldCI6IjVmZTc1YmE5LTIzZWItNDU5Ni04MDI1LTI5MWQxZmYzYmI2OSJ9.2VLlPcNr-exdWVI_jfXjd66Y20rV8KecdzsDutNVqnY"
JWT_SECRET = "123456"